[package]
name = "fast_sssp"
version = "0.1.0"
edition = "2024"
authors = ["jeremy webb <alphastrata@gmail.com>"]
license = "MIT"
description = """
# About:
A naive impl of an SSSP algorithm from the 2025 ["Breaking the Sorting Barrier for Directed Single-Source Shortest Paths"](https://arxiv.org/abs/2504.17033) by Duan, Mao, Mao, Shu, and Yin (2025). 

## Paper claims:

- **Time Complexity**: O(m log^(2/3) n)
- **Space Complexity**: O(n + m)
- **Best for**: Sparse directed graphs where breaking the sorting barrier matters
- **Practical use**: Currently more of theoretical interest; Dijkstra may be faster in practice
"""

[lib]
name = "fast_sssp"

[dependencies]


[dev-dependencies]
criterion = "0.7.0"
rand = "0.9.2"

[[bench]]
harness = false
name = "bench"
path = "benches/sssp_benchmark.rs"
